### ISSUE TITLE
rzuwik powie ze to fake!

### ISSUE THREAD

**Issue by OnlyBis** [Ethyr-UwU/Deobfuscated-Polish-Clients#3]
tak.

**Comment by Rzuwik** [comment]
nie? lol bo ja o tym dawno wiedziałem ty sie teraz obudziłeś? do spania onlybisku

**Comment by OnlyBis** [comment]
idz edytuj aypacka

**Comment by Rzuwik** [comment]
pewnie tak.

**Comment by Rzuwik** [comment]
pokaż mi co mam z aypacka a potem sie wypowiadaj

**Comment by OnlyBis** [comment]
https://youtu.be/IAI5SeqnRjw
^^ wcale

**Comment by Rzuwik** [comment]
może data a i idź sie przypierdalaj do szymeko bo to on najwięcej z aypacka podpierdala nara

**Comment by OnlyBis** [comment]
"JEDNA Z NAJLEPSZYCH PACZEK KOSMETYCZNYCH" TAK XD

**Comment by Rzuwik** [comment]
najnowsza wersja jest bardzo dobra pozatym nie robie jej sam tylko narazie daliśmy sobie przerwe z tbclientem 
a i ps czemu odchodzisz od tematu czyżby ból dupy?

**Comment by OnlyBis** [comment]
https://youtu.be/gs0AIH8XnDc chuj nie masz telewizora i reklamujesz wp? brawo

**Comment by Rzuwik** [comment]
kolejna zmiana tematu #Bóldupy

**Comment by Rzuwik** [comment]
onlybis ośmieszasz się

**Comment by OnlyBis** [comment]
http://tb-client.pl
wasza strona jest taka ze wy nie umiecie dac zdjęcia do serwera

**Comment by OnlyBis** [comment]
+ wypierdalaj

**Comment by Rzuwik** [comment]
sam to zrób

**Comment by Rzuwik** [comment]
pozatym strona jest napisana w pythonie na flasku czyli czymś o czym chuja wiesz

**Comment by Rzuwik** [comment]
do spania czas iść do łóżka onlybisku

**Comment by comfo000** [comment]
prosze do spania onlybis bo czlowieku ja teraz prawie robie rozne rzeczy do tbclienta i zobacz sobie na dc tbclienta ze on nawet jest dobry nie oceniaj ksiazki po okladce byku

**Comment by OnlyBis** [comment]
chyba zamykamy

**Comment by OnlyBis** [comment]
chyba zamykamy

**Comment by comfo000** [comment]
ja cie zaraz zamkne smieciu

**Comment by OnlyBis** [comment]
epic grozenie!

**Comment by OnlyBis** [comment]
@Rzuwik ŻYJESZ????((

**Comment by sadcenter** [comment]
ja pier... To jest github i issue? Zachowujecie sie jakbyscie mieli 8 lat, usuncie ten issue w pizdu i piszcie sobie na discordzie
